import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./_components/common/provider";
import NavbarWrapper from "./_components/common/NavbarWrapper";
import { ToastContainer } from "react-toastify";
import Footer from "./_components/common/footer";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)


{
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
   <ToastContainer position="top-right" autoClose={3000} hideProgressBar />
   <Providers>
       <NavbarWrapper/>
        
          {children}
         <Footer/>
          </Providers>
        
      </body>
    </html>
  );
}
